---
- hosts: dokku
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # One day

    # DOKKU INSTALLATION
    - name: Add 1GB of swap
      become: true
      command: fallocate -l 1G /swapfile
      args:
        creates: /swapfile

    - name: Download the dokku bootstrap script
      get_url:
        url: https://dokku.com/install/v0.30.9/bootstrap.sh
        dest: /tmp/bootstrap.sh
        mode: 0755

    - name: Install dokku
      command: /tmp/bootstrap.sh
      args:
        creates: /usr/local/bin/dokku

    - name: Add ssh key to dokku
      become: true
      command: cat ~/.ssh/authorized_keys | dokku ssh-keys:add admin
      args:
        creates: /home/dokku/.ssh/authorized_keys

    - name: Get list of dokku plugins
      command: dokku plugin:list
      register: dokku_plugin_list

    - name: Install dokku postgres plugin
      command: dokku plugin:install https://github.com/dokku/dokku-postgres.git
      when: "'postgres' not in dokku_plugin_list.stdout"

    - name: Install dokku redis plugin
      command: dokku plugin:install https://github.com/dokku/dokku-redis.git redis
      when: "'redis' not in dokku_plugin_list.stdout"
