- name: Install rclone
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - rclone

- name: Ensure rclone config directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.config/rclone"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: Upload rclone B2 config
  ansible.builtin.template:
    src: "./immich/rclone.conf"
    dest: "/home/{{ ansible_user }}/.config/rclone/rclone.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

