networks:
  caddy_caddynet:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3101:3001
    restart: always
    networks:
      - caddy_caddynet
