version: "3"
services:
  healthchecks:
    image: healthchecks/healthchecks:latest
    container_name: healthchecks
    environment:
      - ALLOWED_HOSTS=healthchecks.chibi.rodeo,192.168.178.200
      - DB=sqlite
      - DB_NAME=/data/hc.sqlite
      - DEBUG=False
      - DEFAULT_FROM_EMAIL=fixme-email-address-here
      - EMAIL_HOST=fixme-smtp-host-here
      - EMAIL_HOST_PASSWORD=fixme-smtp-password-here
      - EMAIL_HOST_USER=fixme-smtp-username-here
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - SECRET_KEY=---
      - TELEGRAM_BOT_NAME={TELEGRAM_BOT_NAME}
      - TELEGRAM_TOKEN={TELEGRAM_BOT_TOKEN}
      - SITE_ROOT=https://healthchecks.chibi.rodeo
    ports:
      - 8020:8000
    volumes:
      - healthchecks-data:/data
    restart: unless-stopped
    networks:
      - caddy_caddynet
volumes:
    healthchecks-data:

networks:
  caddy_caddynet:
    external: true
