version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 999
    ports:
      - 3015:3000
    volumes:
      # - /storage-pool/apps/homepage/config:/app/config # Make sure your local config directory exists
      - ./app/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
