---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=999
      - PGID=1000
      - TZ=Etc/UTC
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /storage-pool/apps/jellyfin/library:/config
      - /storage-pool/apps/jellyfin/tvseries:/data/tvshows
      - /storage-pool/apps/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
