---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

homelab-prod:
  socket: /var/run/docker.sock

# nas:
#   host: 192.168.178.200
#   port: 2375
# my-docker:
