---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Immich:
        href: https://immich.chibi.rodeo/
        server: homelab-prod
        container: immich_server
        icon: immich
        siteMonitor: https://immich.chibi.rodeo/
        widget:
            type: immich
            url: https://immich.chibi.rodeo
            key: tOScguzDW1MnJp6gvuYf1C9fyDnQCiVwOWKfIdQOZY
    - Jellyfin:
        href: http://192.168.178.200:8096
        server: homelab-prod
        icon: jellyfin
        container: jellyfin
        siteMonitor: http://192.168.178.200:8096

- Applications:
    - Kling:
        href: https://kling.frey.today/api/v1/portfolios/9583bafb-28c4-411a-9567-1172a00f6944.json
        server: kling.frey.today
        siteMonitor: https://kling.frey.today
        widget:
            type: customapi
            url: https://kling.frey.today/api/v1/portfolios/9583bafb-28c4-411a-9567-1172a00f6944.json
            refreshInterval: 300000
            method: GET
            mappings:
                - field: total_worth
                  label: Total Worth
                  type: text
                  suffix: "$"
                - field: profit_and_loss
                  label: PNL
                  type: number
                  suffix: "$"
                - field: percent_change
                  label: Percent Change
                  type: text
                  decimals: 2
                  suffix: "%"
    - PiHole:
        href: https://pihole.chibi.rodeo/admin/index.php
        server: homelab-prod
        container: pihole
        siteMonitor: https://pihole.chibi.rodeo/admin/index.php
        widget:
            type: pihole
            url: https://pihole.chibi.rodeo
            key: ae88dd40a2413f6063c753382c26cb427f3a4d4d0cb082889d2ca28af70bfa88
    - UptimeKuma:
        href: https://uptime.chibi.rodeo
        widget:
            type: uptimekuma
            url: https://uptime.chibi.rodeo
            slug: everything
        siteMonitor: http://192.168.178.200:3000
    - Proxmox:
        href: https://192.168.178.201:8006
        siteMonitor: https://192.168.178.201:8006
        icon: proxmox
        widget:
            type: proxmox
            url: https://192.168.178.201:8006
            username: api@pam!api
            password: 9cf7ef06-e143-4b77-be11-78075614b1c2
            node: pve-1 # optional
    - Dawarich:
        href: http://192.168.178.200:3000
        server: homelab-prod
        container: dawarich_app
    - Gitea:
        href: https://gitea.chibi.rodeo
        server: homelab-prod
        container: gitea
        icon: gitea
        siteMonitor: https://gitea.chibi.rodeo
    - OwnTracks:
        href: http://192.168.178.200:8085
        server: homelab-prod
        container: owntracks-owntracks-frontend-1
        siteMonitor: http://192.168.178.200:8085
    - FritzBox:
        href: http://192.168.178.1
        ping: fritz.box
        icon: avmfritzbox.png

- Statistics (Prod):
    - CPU Usage:
        widget:
            type: glances
            url: http://192.168.178.200:61208
            metric: cpu
            chart: false
    - Network Usage:
        widget:
            type: glances
            url: http://192.168.178.200:61208
            metric: network:eth0
            chart: false
    - Memory Usage:
        widget:
            type: glances
            url: http://192.168.178.200:61208
            metric: memory
            chart: false
    - Disk Usage:
        widget:
            type: glances
            url: http://192.168.178.200:61208
            metric: disk:sda
            chart: false

- Todo:
    - Excalidraw:
        href: http://192.168.178.200:8013
        server: homelab-prod
        container: excalidraw
        icon: excalidraw
        siteMonitor: http://192.168.178.200:8013
    - Healthchecks:
        href: http://192.168.178.200:8020
        server: homelab-prod
        icon: healthchecks
        container: healthchecks
        siteMonitor: http://192.168.178.200:8020
        widget:
            type: healthchecks
            url: http://192.168.178.200:8020
            key: e50MntPtFuy__n0DvlL7UVsdaDfV4Woq
            uuid: e57e334c-fad8-42b2-a9f1-730a09d6d705
    - PaperlessNGX:
        href: http://192.168.178.200:8010
        server: homelab-prod
        container: paperlessngx-webserver-1
        siteMonitor: http://192.168.178.200:8010
        icon: paperless
