---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    label: System
    cpu: true
    memory: true
    cputemp: true
    uptime: true

- resources:
    label: Storage
    expanded: true
    disk:
      - /storage-pool
