---
  - hosts: dokku
    tasks:
      - name: create certs directory
        file:
          path: /root/certs
          state: directory
          owner: root
          group: root
          mode: 0755

      - name: upload certificate files to server
        copy:
          src: "{{item}}"
          dest: "/root/certs"
          owner: root
          group: root
          mode: 0644
        with_items:
          - "tmp/{{app_domain}}.crt"
          - "tmp/{{app_domain}}.key"

      - name: tar certificate file
        command: tar -cvf /root/certs/{{app_domain}}.tar /root/certs/{{app_domain}}.crt /root/certs/{{app_domain}}.key

      - name: copy certificate file to dokku
        shell:
          cmd: dokku certs:add {{app_name}} < {{app_domain}}.tar
          chdir: /root/certs

      - name: rebuild proxy config
        command: dokku proxy:build-config {{app_name}}
