---

- name: Rename host
  import_playbook: rename_host.yml

- name: Install ZFS
  import_playbook: install_zfs.yml

- name: Upgrade APT packages
  import_playbook: apt-upgrade.yml

- name: Install Docker
  import_playbook: install_docker.yml

- name: Install Portainer
  import_playbook: install_portainer.yml

- name: Install Caddy
  import_playbook: install_caddy.yml

- name: Install Glances
  import_playbook: install_glances.yml

- name: Install Immich
  import_playbook: install_immich.yml

- name: Install Jellyfin
  import_playbook: install_jellyfin.yml

