# This script is responsible for ZFS installation

---
- hosts: homelab-fuji
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml

    - name: Install Zfs
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - zfsutils-linux
