# This script is responsible for Immich installation

---
- hosts: immich
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml

    - name: Create directory for Immich
      file:
        path: "{{ local_immich_path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Download Immich docker-compose.yml
      get_url:
        url: "https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml"
        dest: "{{ local_immich_path }}/docker-compose.yml"
        mode: 0644

    - name: Download Immich .env file
      get_url:
        url: "https://github.com/immich-app/immich/releases/latest/download/example.env"
        dest: "{{ local_immich_path }}/.env"
        mode: 0644

    - name: Replace UPLOAD_LOCATION in .env file
      lineinfile:
        path: "{{ local_immich_path }}/.env"
        regexp: '^UPLOAD_LOCATION=.*$'
        line: "UPLOAD_LOCATION={{ local_immich_path }}/app"

    - pip: name=docker-compose

    - name: Create and start services
      community.docker.docker_compose:
        project_src: "{{ local_immich_path }}"
      register: output

    - name: Install rclone
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - rclone

    - name: Upload rclone B2 config
      template:
        src: "tmp/rclone.conf"
        dest: ".config/rclone/rclone.conf"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600

    - name: Schedule Immich DB backup to be done daily
      cron:
        name: "Dump Immich DB to a local file"
        minute: "45"
        hour: "5"
        job: docker exec -t immich_postgres pg_dumpall -c -U postgres | gzip > "{{ local_backup_path }}/db_dump.sql.gz" && curl -X GET {{ healthchecks_ping_url }}{{ hc_immich_backup_uuid }}
        state: present

    - name: Schedule photos backup to be done once a month
      cron:
        name: "Backup immich files to B2"
        minute: "55"
        hour: "3"
        day: "15"
        job: /usr/bin/rclone sync {{ local_backup_path }} {{ backblaze_remote_name }}:{{ backblaze_bucket_name }} --config /home/{{ ansible_user }}/.config/rclone/rclone.conf --include='/app/library/**' --include='/app/upload/**' --include='/app/profile/**' && curl -X GET {{ healthchecks_ping_url }}{{ hc_immich_backup_uploaded_uuid }}
        state: present
