# https://hub.docker.com/r/linuxserver/jellyfin

---
- hosts: nas
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml

    - name: Create directory for Jellyfin
      file:
        path: "{{ local_jellyfin_path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Create directory for Jellyfin config
      file:
        path: "{{ local_jellyfin_storage_path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Upload jellyfin docker-compose
      template:
        src: "jellyfin/docker-compose.yml"
        dest: "{{ local_jellyfin_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600

    - name: Create and start services
      community.docker.docker_compose:
        project_src: "{{ local_jellyfin_path }}"
      register: output


