# This script is responsible for Immich installation

---
- hosts: homelab-prod
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml

    - name: Create directory for Actual
      file:
        path: "{{ local_apps_path }}/actual_budget"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Upload Actual docker-compose.yml
      template:
        src: "actual/docker-compose.yml"
        dest: "{{ local_apps_path }}/actual_budget/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600

    - name: Stop existing services
      command: docker compose -f {{ local_apps_path }}/actual_budget/docker-compose.yml stop

    - name: Create and start services
      command: docker compose -f {{ local_apps_path }}/actual_budget/docker-compose.yml up -d
