# https://hub.docker.com/r/linuxserver/jellyfin

---
- hosts: homelab-prod
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml

    - name: Create directory for Jellyfin
      file:
        path: "{{ local_apps_path }}/jelly"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Create all necessary directories
      file:
        path: "{{ local_apps_storage_path }}/jelly/{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      loop:
        - library
        - tvseries
        - movies

    - name: Set recursive permissions for Jellyfin config
      file:
        path: "{{ local_apps_storage_path }}/jelly"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
        recurse: true

    - name: Upload jellyfin docker-compose
      template:
        src: "jellyfin/docker-compose.yml"
        dest: "{{ local_apps_path }}/jelly/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600

    - name: Stop existing services
      command: docker compose -f {{ local_apps_path }}/jelly/docker-compose.yml up -d

    - name: Create and start services
      command: docker compose -f {{ local_apps_path }}/jelly/docker-compose.yml up -d

