# https://hub.docker.com/r/linuxserver/jellyfin

---
- hosts: homelab-prod
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml

    - name: Create directory for Jellyfin
      file:
        path: "{{ local_apps_path }}/jellyfin"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Create directory for Jellyfin config
      file:
        path: "{{ local_apps_storage_path }}/jellyfin"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Upload jellyfin docker-compose
      template:
        src: "jellyfin/docker-compose.yml"
        dest: "{{ local_apps_path }}/jellyfin/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600

    - name: Create and start services
      command: docker compose -f {{ local_apps_path }}/jellyfin/docker-compose.yml up -d


