---
- hosts: dokku
  vars:
    dokku_version: "0.31.4"
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml
    - import_tasks: ../tasks/rename_host.yml
      vars:
        hostname: dokku-hetzner

    # DOKKU INSTALLATION
    ## TODO: Add crontask setup for docker system prune -a
    - name: Add 3GB of swap
      become: true
      command: fallocate -l 3G /swapfile
      args:
        creates: /swapfile

    - name: Download the dokku bootstrap script
      get_url:
        url: https://dokku.com/install/v{{ dokku_version }}/bootstrap.sh
        dest: /tmp/bootstrap.sh
        mode: 0755

    - name: Install dokku
      command: /tmp/bootstrap.sh
      args:
        creates: /usr/local/bin/dokku

    - name: Add ssh key to dokku
      become: true
      command: cat ~/.ssh/authorized_keys | dokku ssh-keys:add admin
      args:
        creates: /home/dokku/.ssh/authorized_keys

    - name: Get list of dokku plugins
      command: dokku plugin:list
      register: dokku_plugin_list

    - name: Install dokku postgres plugin
      command: dokku plugin:install https://github.com/dokku/dokku-postgres.git
      when: "'postgres' not in dokku_plugin_list.stdout"

    - name: Install dokku redis plugin
      command: dokku plugin:install https://github.com/dokku/dokku-redis.git redis
      when: "'redis' not in dokku_plugin_list.stdout"
