---
- hosts: homelab-prod
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml

    - name: Create directory for lubelogger
      file:
        path: "{{ local_apps_path }}/lubelogger"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Copy necessafy files
      copy:
        src: '{{item}}'
        dest: "{{ local_apps_path }}/lubelogger"
        owner: root
        group: root
        mode: 0644
      loop:
        - ./lubelogger/docker-compose.yml
        - ./lubelogger/.env

    - name: Stop existing services
      command: docker compose -f {{ local_apps_path }}/lubelogger/docker-compose.yml up -d

    - name: Create and start services
      command: docker compose -f {{ local_apps_path }}/lubelogger/docker-compose.yml up -d

