# This script is responsible for pihole installation

---
- hosts: homelab-prod
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml

    - name: Create directory for pihole
      file:
        path: "{{ local_apps_path }}/pihole"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Upload pihole docker-compose.yml
      copy:
        src: ./pihole/docker-compose.yml
        dest: "{{ local_apps_path }}/pihole/docker-compose.yml"
        mode: 0644

    - name: Create and start services
      command: docker compose -f {{ local_apps_path }}/pihole/docker-compose.yml up -d


