# This script is responsible for OwnTracks installation

---
- hosts: homelab-prod
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml

    - name: Create directory for owntracks
      file:
        path: "{{ local_apps_path }}/owntracks"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Upload Owntracks docker-compose.yml
      copy:
        src: ./owntracks/docker-compose.yml
        dest: "{{ local_apps_path }}/owntracks/docker-compose.yml"
        mode: 0644

    - name: Create and start services
      command: docker compose -f {{ local_apps_path }}/owntracks/docker-compose.yml up -d


