---
- hosts: homelab-prod
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml

    - name: Create directory for vaultwarden
      file:
        path: "{{ local_apps_path }}/vaultwarden"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Copy necessafy files
      copy:
        src: '{{item}}'
        dest: "{{ local_apps_path }}/vaultwarden"
        owner: root
        group: root
        mode: 0644
      loop:
        - ./vaultwarden/docker-compose.yml

    - name: Stop existing services
      command: docker compose -f {{ local_apps_path }}/vaultwarden/docker-compose.yml up -d

    - name: Create and start services
      command: docker compose -f {{ local_apps_path }}/vaultwarden/docker-compose.yml up -d

