# This script is responsible for Immich installation

---
- hosts: homelab-fuji
  tasks:
    - import_tasks: ../tasks/apt-upgrade.yml
    - import_tasks: ../tasks/install_rclone.yml

    - name: Create directory for Immich
      file:
        path: "{{ local_apps_path }}/immich"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Upload Immich docker-compose.yml
      copy:
        src: ./immich/docker-compose.yml
        dest: "{{ local_apps_path }}/immich/docker-compose.yml"
        mode: 0644

    - name: Upload Immich env vars
      template:
        src: ./immich/example.env
        dest: "{{ local_apps_path }}/immich/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644

    - name: Install pipx
      ansible.builtin.apt:
        name: pipx
        state: present

    - name: Ensure pipx binary is accessible
      ansible.builtin.shell: |
        python3 -m pipx ensurepath

    - name: Install docker-compose using pipx
      ansible.builtin.shell: |
        pipx install docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Stop existing services
      command: docker compose -f {{ local_apps_path }}/immich/docker-compose.yml up -d

    - name: Create and start services
      command: docker compose -f {{ local_apps_path }}/immich/docker-compose.yml up -d

    - name: Create directory if they don't exist
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0775
      loop:
        - "{{ local_pool_path }}/tasks/immich/"
        - "{{ local_backups_path }}/immich"


    - name: Upload Immich backup script
      template:
        src: "./immich/backup.sh"
        dest: "{{ local_pool_path }}/tasks/immich/backup.sh"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0700

    - name: Schedule Immich DB backup to be done monthly
      cron:
        name: "Dump Immich DB to a local file"
        minute: "45"
        hour: "5"
        day: "1"
        job: "{{ local_pool_path }}/tasks/immich/backup.sh"
        state: present
