---
- hosts: homelab
  vars:
    local_backup_path: /home/{{ ansible_user }}/backups/paperlessngx/export
    backblaze_bucket_name: frey-homelab-backups
    backblaze_remote_name: homelab-backup
  tasks:
    # - name: Update and upgrade apt packages
    #   apt:
    #     upgrade: yes
    #     update_cache: yes
    #     cache_valid_time: 86400 # One day

    # - name: Install rclone
    #   apt:
    #     name: "{{ packages }}"
    #     state: present
    #     update_cache: yes
    #   vars:
    #     packages:
    #       - rclone

    # - name: Upload rclone B2 config
    #   template:
    #     src: "tmp/rclone.conf"
    #     dest: ".config/rclone/rclone.conf"
    #     owner: "{{ ansible_user }}"
    #     group: "{{ ansible_user }}"
    #     mode: 0600

    - name: Schedule Paperless backup to be done twice a month
      cron:
        name: "Export Paperless documents"
        minute: "*"
        # hour: "5"
        # day: "1,15"
        job: docker ps --format "'{{'.Names'}}'" | grep paperlessngx-webserver | xargs -I {} docker exec {} document_exporter ../export && docker ps --format "'{{'.Names'}}'" | grep paperlessngx-webserver | xargs -I {} docker cp {}:/usr/src/paperless/export /home/{{ ansible_user }}/backups/paperlessngx/export
        state: present

    - name: Schedule Paperless backup to be done twice a month
      cron:
        name: "Backup Paperless documents to B2"
        minute: "*"
        # hour: "5"
        # day: "1,15"
        job: /usr/bin/rclone sync {{ local_backup_path }} {{ backblaze_remote_name }}:{{ backblaze_bucket_name }}/paperlessngx/export --config /home/{{ ansible_user }}/.config/rclone/rclone.conf
        state: present

    - name: Schedule removing Paperless backup
      cron:
        name: "Remove Paperless backup"
        minute: "*"
        hour: "10"
        day: "2,16"
        job: rm -rf {{ local_backup_path }}/*
        state: present
