---
- hosts: homelab-prod
  tasks:
    - name: Copy necessafy files
      copy:
        src: '{{item}}'
        dest: "{{ local_apps_path }}/caddy"
        owner: root
        group: root
        mode: 0644
      loop:
        - ./caddy/Caddyfile

    - name: Replace CLOUDFLARE_API_TOKEN in Caddyfile
      replace:
        path: "{{ local_apps_path }}/caddy/Caddyfile"
        regexp: 'dns cloudflare 123'
        replace: "    dns cloudflare {{ cf_api_token }}"

    - name: Restart existing services
      command: docker compose -f {{ local_apps_path }}/caddy/docker-compose.yml restart
